# Generated by Django 4.2.4 on 2023-08-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
